const {test,expect}=require("@playwright/test");
test("D18: three modes are actionable and dragon remains intact",async({page})=>{
  await page.goto("/");
  await expect(page.locator('#flow-guide')).toHaveAttribute("data-ready","true",{timeout:12000});
  const modes=page.locator("button[data-studio-mode]");
  await expect(modes).toHaveCount(3);
  await expect(page.locator(".flow-console")).toBeVisible();
  await modes.nth(1).evaluate(element=>element.click());
  await expect(page.locator("#instructor-flow")).toHaveAttribute("data-studio-mode","breath");
  await expect(page.locator(".flow-console")).toBeHidden();
  await expect(page.locator("#studio-guided")).toBeVisible();
  await expect(page.locator("#studio-guided-countdown")).toHaveText("05:00");
  await page.keyboard.press("s");
  await expect(page.locator(".flow-console")).toHaveAttribute("data-flow-status","idle");
  await page.locator('[data-studio-duration-index="0"]').evaluate(el=>el.click());
  await expect(page.locator("#studio-guided-countdown")).toHaveText("03:00");
  await page.locator('[data-studio-action="primary"]').evaluate(el=>el.click());
  await expect(page.locator("#studio-guided")).toHaveAttribute("data-studio-status","running");
  await expect(modes.nth(2)).toBeDisabled();
  await page.locator('[data-studio-action="primary"]').evaluate(el=>el.click());
  await expect(page.locator("#studio-guided")).toHaveAttribute("data-studio-status","paused");
  await page.locator('[data-studio-action="reset"]').evaluate(el=>el.click());
  await expect(page.locator("#studio-guided")).toHaveAttribute("data-studio-status","idle");
  await modes.nth(2).evaluate(el=>el.click());
  await expect(page.locator("#studio-guided-countdown")).toHaveText("10:00");
  await modes.nth(0).evaluate(el=>el.click());
  await expect(page.locator(".flow-console")).toBeVisible();
  await expect(page.locator("#studio-guided")).toBeHidden();
  await expect(page.locator('#flow-guide')).toHaveAttribute("data-ready","true");
});
test("D18: mobile layout has no horizontal overflow and respects reduced motion",async({page})=>{
  await page.setViewportSize({width:320,height:780});
  await page.emulateMedia({reducedMotion:"reduce"});
  await page.goto("/");
  await page.locator('[data-studio-mode="breath"]').evaluate(el=>el.click());
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await expect(page.locator(".studio-breath-orb")).toHaveCSS("transition-duration","0s");
  await page.locator('[data-studio-action="primary"]').evaluate(el=>el.click());
  await expect(page.locator("#studio-guided")).toHaveAttribute("data-studio-status","running");
});
