const {test,expect}=require("@playwright/test");
test("D20: personalized practice timings and Yin/Yang never change Flow order",async({page})=>{
 await page.goto("/");
 await expect(page.locator("#flow-guide")).toHaveAttribute("data-ready","true",{timeout:12000});
 const controls=page.locator("button[data-studio-plan]");
 await expect(controls).toHaveCount(3);
 await controls.nth(0).evaluate(el=>el.click());
 await expect(page.locator("#instructor-flow")).toHaveAttribute("data-studio-pace","gentle");
 await expect(page.locator("#flow-guide")).toHaveAttribute("data-spirit","yin");
 await page.locator('[data-flow-action="start"]').evaluate(el=>el.click());
 await expect(page.locator("#flow-phase-target")).toHaveText("00:24");
 await expect(controls.nth(2)).toBeDisabled();
 await page.locator('[data-flow-action="reset"]').evaluate(el=>el.click());
 await expect(controls.nth(2)).toBeEnabled();
 await controls.nth(2).evaluate(el=>el.click());
 await expect(page.locator("#flow-guide")).toHaveAttribute("data-spirit","yang");
 await page.locator('[data-flow-action="start"]').evaluate(el=>el.click());
 await expect(page.locator("#flow-phase-target")).toHaveText("00:36");
});
test("D20: rhythm preference survives reload and hides in guided paths",async({page})=>{
 await page.goto("/");
 await expect(page.locator("#flow-guide")).toHaveAttribute("data-ready","true",{timeout:12000});
 await page.locator('button[data-studio-plan="deep"]').evaluate(el=>el.click());
 await page.reload();
 await expect(page.locator('#instructor-flow')).toHaveAttribute("data-studio-pace","deep");
 await expect(page.locator('button[data-studio-plan="deep"]')).toHaveAttribute("aria-pressed","true");
 await page.locator('button[data-studio-mode="meditation"]').evaluate(el=>el.click());
 await expect(page.locator(".studio-plan")).toBeHidden();
 await page.locator('button[data-studio-mode="asanas"]').evaluate(el=>el.click());
 await expect(page.locator(".studio-plan")).toBeVisible();
});
