const {test,expect}=require("@playwright/test");
test("V36: three visible controls share exactly one audio source and always start silent",async({page})=>{
 await page.goto("/");
 await expect(page.locator("#audio-play")).toHaveAttribute("data-audio-ready","true");
 const audio=page.locator("#focus-audio");
 await expect(audio).toHaveCount(1);
 await expect(page.locator("audio")).toHaveCount(1);
 expect(await audio.evaluate(el=>el.paused)).toBe(true);
 expect(await audio.evaluate(el=>new URL(el.currentSrc||el.src).pathname.endsWith("/audio/silence-between-notes.mp3"))).toBe(true);
 await page.locator("#audio-play").evaluate(el=>el.click());
 await expect.poll(()=>audio.evaluate(el=>el.paused),{timeout:10000}).toBe(false);
 await page.locator(".sanctuary-music").evaluate(el=>el.click());
 await expect.poll(()=>audio.evaluate(el=>el.paused)).toBe(false);
 await expect(page.locator(".sanctuary-music")).toHaveAttribute("aria-pressed","true");
 await page.locator(".sanctuary-music").evaluate(el=>el.click());
 await expect.poll(()=>audio.evaluate(el=>el.paused)).toBe(true);
 await page.locator('[data-studio-mode="breath"]').evaluate(el=>el.click());
 const studio=page.locator(".studio-soundscape");
 await expect(studio).toBeVisible();
 await studio.locator(".studio-sound-toggle").evaluate(el=>el.click());
 await expect.poll(()=>audio.evaluate(el=>el.paused),{timeout:10000}).toBe(false);
 await expect(page.locator("audio")).toHaveCount(1);
 await studio.locator(".studio-sound-toggle").evaluate(el=>el.click());
 await expect.poll(()=>audio.evaluate(el=>el.paused)).toBe(true);
});
test("V36: Vortex uses explicit opt-in and yields to main soundtrack",async({page})=>{
 await page.route("https://vortex-gilt-xi.vercel.app/**",route=>route.fulfill({contentType:"text/html",body:"<html><body>Vortex preview</body></html>"}));
 await page.goto("/");
 const frame=page.locator(".campo-vortex-full iframe");
 await expect(frame).toHaveAttribute("src","about:blank");
 await expect(page.locator("#vortex-activate")).toBeVisible();
 await page.locator("#audio-play").evaluate(el=>el.click());
 await expect.poll(()=>page.locator("#focus-audio").evaluate(el=>el.paused)).toBe(false);
 await page.locator("#vortex-activate").evaluate(el=>el.click());
 await expect.poll(()=>page.locator("#focus-audio").evaluate(el=>el.paused)).toBe(true);
 await expect(frame).toHaveAttribute("src","https://vortex-gilt-xi.vercel.app/");
 await page.locator("#audio-play").evaluate(el=>el.click());
 await expect.poll(()=>page.locator("#focus-audio").evaluate(el=>el.paused),{timeout:10000}).toBe(false);
 await expect(frame).toHaveAttribute("src","about:blank");
 await expect(page.locator("#vortex-activate")).toBeVisible();
});
test("V36: visibly stronger chest breath freezes when paused, reduced motion remains still",async({page})=>{
 await page.goto("/");
 await page.locator('[data-studio-mode="breath"]').evaluate(el=>el.click());
 await page.locator('[data-studio-action="primary"]').evaluate(el=>el.click());
 const guided=page.locator("#studio-guided");
 await expect(guided).toHaveAttribute("data-studio-status","running");
 await expect.poll(()=>guided.evaluate(el=>+el.style.getPropertyValue("--studio-guardian-expansion")),{timeout:5000}).toBeGreaterThan(1.025);
 const value=await guided.evaluate(el=>el.style.getPropertyValue("--studio-guardian-expansion"));
 await page.locator('[data-studio-action="primary"]').evaluate(el=>el.click());
 await page.waitForTimeout(650);
 expect(await guided.evaluate(el=>el.style.getPropertyValue("--studio-guardian-expansion"))).toBe(value);
 await page.emulateMedia({reducedMotion:"reduce"});
 await expect(page.locator(".studio-breath-dragon .sd31-breath-core")).toHaveCSS("transform","none");
});
