/* D24 · Three new hand-authored asanas. The D17 SVG anatomy is shared,
   but every shoulder, arm, hip, knee and contact point is a new composition.
   These are optional explorations: the original 10-step Flow remains intact. */
(() => {
  "use strict";
  const poses = [
    {
      id:"d24-mountain",kind:"mountain",
      name:["Montaña · Tadasana","Mountain · Tadasana"],
      cue:["Erguido y estable. Afloja los hombros, reparte el peso en ambos pies.",
           "Stand comfortably. Soften the shoulders and feel both feet grounded."],
      support:["Dos pies en el suelo; brazos relajados.","Both feet planted; arms relaxed."],
      body:[359,219,58,91,0],head:[359,107,.82,0,"closed"],
      arms:["M308 188Q287 235 278 317","M411 188Q435 239 441 317"],
      legs:["M331 290Q328 335 328 381","M386 290Q392 335 393 381"],
      hands:[[278,317],[441,317]],feet:[[328,381],[393,381]],
      tail:[426,257,.58,-9]
    },
    {
      id:"d24-downward",kind:"downward",
      name:["Perro boca abajo · Adho Mukha Svanasana","Downward dog · Adho Mukha Svanasana"],
      cue:["Eleva la pelvis como una montaña y reparte el apoyo entre manos y pies. Dobla las rodillas si lo necesitas.",
           "Lift the hips into an inverted V. Share the weight across hands and feet; bend the knees if helpful."],
      support:["Cuatro apoyos; evita empujar la cabeza hacia el suelo.","Four contact points; do not force the head towards the mat."],
      body:[361,234,118,46,-25],head:[206,303,.68,-49,"closed"],
      arms:["M292 249Q232 310 173 370","M315 266Q276 321 230 383"],
      legs:["M431 238Q483 278 499 378","M459 220Q528 278 547 373"],
      hands:[[173,370],[230,383]],feet:[[499,378],[547,373]],
      tail:[467,189,.61,-39]
    },
    {
      id:"d24-butterfly",kind:"butterfly",
      name:["Mariposa · Baddha Konasana","Butterfly · Baddha Konasana"],
      cue:["Siéntate alto y acerca suavemente las plantas de los pies. Deja que las rodillas descansen.",
           "Sit upright and gently bring the soles towards each other. Let the knees settle naturally."],
      support:["Pelvis apoyada; rodillas libres, sin empujarlas.","Seated pelvis; never press the knees down."],
      body:[359,265,68,84,0],head:[360,144,.85,0,"closed"],
      arms:["M308 232Q278 283 319 343","M411 232Q440 283 400 343"],
      legs:["M326 316Q251 332 315 366","M391 316Q471 332 404 366"],
      hands:[[319,343],[400,343]],feet:[[315,366],[404,366]],
      tail:[429,280,.62,9]
    }
  ];
  // All positions and limbs are authored, not generated by reflecting one side.
  const names = poses.map(p=>p.id);
  if(new Set(names).size!==poses.length)throw Error("Duplicate asana identifiers");
  for(const pose of poses){
    if(pose.arms.length!==2||pose.legs.length!==2||pose.hands.length!==2||pose.feet.length!==2)
      throw Error("Each asana requires exactly four distinct limbs and contact points");
    for(const point of [...pose.hands,...pose.feet]){
      if(!point.every(v=>Number.isFinite(v)&&v>=0&&v<=720))
        throw Error("Asana contact outside SVG viewBox");
    }
    Object.freeze(pose.hands);Object.freeze(pose.feet);
    Object.freeze(pose.arms);Object.freeze(pose.legs);
    Object.freeze(pose);
  }
  const api=Object.freeze({
    poses:Object.freeze(poses),
    byId:id=>poses.find(p=>p.id===id)||null
  });
  if(typeof window!=="undefined")window.YOGA_ASANA_LIBRARY=api;
  if(typeof module!=="undefined"&&module.exports)module.exports=api;
})();
