import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";

const index = readFileSync(new URL("../index.html", import.meta.url), "utf8");
const ui = readFileSync(new URL("../instructor-ui.js", import.meta.url), "utf8");
const main = readFileSync(new URL("../main.js", import.meta.url), "utf8");
const i18n = readFileSync(new URL("../i18n.js", import.meta.url), "utf8");
const css = readFileSync(new URL("../styles.css", import.meta.url), "utf8");

test("200Q 001: flow section exists",()=>assert.ok(index.includes('id="instructor-flow"')));
test("200Q 002: flow title exists",()=>assert.ok(index.includes('id="instructor-flow-title"')));
test("200Q 003: phase label exists",()=>assert.ok(index.includes('id="flow-phase-label"')));
test("200Q 004: phase meta exists",()=>assert.ok(index.includes('id="flow-phase-meta"')));
test("200Q 005: phase cue exists",()=>assert.ok(index.includes('id="flow-phase-cue"')));
test("200Q 006: session clock exists",()=>assert.ok(index.includes('id="flow-session-time"')));
test("200Q 007: phase target exists",()=>assert.ok(index.includes('id="flow-phase-target"')));
test("200Q 008: phase remaining exists",()=>assert.ok(index.includes('id="flow-phase-time"')));
test("200Q 009: flow state exists",()=>assert.ok(index.includes('id="flow-state"')));
test("200Q 010: flow progress exists",()=>assert.ok(index.includes('id="flow-progress-bar"')));
test("200Q 011: phase progress exists",()=>assert.ok(index.includes('id="flow-phase-progress-bar"')));
test("200Q 012: controls group exists",()=>assert.ok(index.includes('class="flow-controls"')));
test("200Q 013: previous control exists",()=>assert.ok(index.includes('data-flow-action="previous"')));
test("200Q 014: pause control exists",()=>assert.ok(index.includes('data-flow-action="pause"')));
test("200Q 015: next control exists",()=>assert.ok(index.includes('data-flow-action="next"')));
test("200Q 016: reset control exists",()=>assert.ok(index.includes('data-flow-action="reset"')));
test("200Q 017: start control exists",()=>assert.ok(index.includes('data-flow-action="start"')));
test("200Q 018: sequence label exists",()=>assert.ok(index.includes('data-i18n="flowSequence"')));
test("200Q 019: practice progress is a progressbar",()=>assert.ok(/class="flow-progress"[^>]*role="progressbar"/.test(index)));
test("200Q 020: phase label is polite live region",()=>assert.ok(/id="flow-phase-label"[^>]*aria-live="polite"/.test(index)));
test("200Q 021: engine API binding",()=>assert.ok(ui.includes("window.YOGA_FLOW")));
test("200Q 022: session API binding",()=>assert.ok(ui.includes("window.YOGA_SESSION")));
test("200Q 023: phase API binding",()=>assert.ok(ui.includes("window.YOGA_PHASE")));
test("200Q 024: engine factory used",()=>assert.ok(ui.includes("engineApi.create()")));
test("200Q 025: session factory used",()=>assert.ok(ui.includes("sessionApi.create()")));
test("200Q 026: phase factory used",()=>assert.ok(ui.includes("phaseApi.create()")));
test("200Q 027: renderSession exists",()=>assert.ok(ui.includes("const renderSession = () =>")));
test("200Q 028: formatTime exists",()=>assert.ok(ui.includes("const formatTime = (seconds) =>")));
test("200Q 029: phase sync exists",()=>assert.ok(ui.includes("const syncPhaseClock = (snapshot) =>")));
test("200Q 030: phase reset is wired",()=>assert.ok(ui.includes("phase.reset()")));
test("200Q 031: phase start is wired",()=>assert.ok(ui.includes("phase.start()")));
test("200Q 032: phase pause is wired",()=>assert.ok(ui.includes("phase.pause()")));
test("200Q 033: phase resume is wired",()=>assert.ok(ui.includes("phase.resume()")));
test("200Q 034: phase remaining is rendered",()=>assert.ok(ui.includes("const remaining = Math.max(0, duration - elapsed)")));
test("200Q 035: phase cue is rendered",()=>assert.ok(ui.includes("phaseCue.textContent")));
test("200Q 036: phase target is rendered",()=>assert.ok(ui.includes("phaseTarget.textContent")));
test("200Q 037: phase progress is rendered",()=>assert.ok(ui.includes("phaseProgress.style.transform")));
test("200Q 038: language change re-renders flow",()=>assert.ok(ui.includes("render(engine.snapshot())")));
test("200Q 039: start action synchronizes clocks",()=>assert.ok(/start: \(\) => \{ session\.start\(\); phase\.start\(\); engine\.start\(\);/.test(ui)));
test("200Q 040: reset action synchronizes clocks",()=>assert.ok(/reset: \(\) => \{ session\.reset\(\); phase\.reset\(\); engine\.reset\(\);/.test(ui)));
test("200Q 041: focus player exists",()=>assert.ok(index.includes('id="focus-player"')));
test("200Q 042: audio element exists",()=>assert.ok(index.includes('id="focus-audio"')));
test("200Q 043: play button exists",()=>assert.ok(index.includes('id="audio-play"')));
test("200Q 044: mute button exists",()=>assert.ok(index.includes('id="audio-mute"')));
test("200Q 045: volume control exists",()=>assert.ok(index.includes('id="audio-vol"')));
test("200Q 046: seek control exists",()=>assert.ok(index.includes('id="audio-seek"')));
test("200Q 047: current time exists",()=>assert.ok(index.includes('id="audio-cur"')));
test("200Q 048: duration exists",()=>assert.ok(index.includes('id="audio-dur"')));
test("200Q 049: audio preloads metadata",()=>assert.ok(/id="focus-audio"[^>]*preload="metadata"/.test(index)));
test("200Q 050: audio loops",()=>assert.ok(/id="focus-audio"[^>]*loop/.test(index)));
test("200Q 051: play handler exists",()=>assert.ok(main.includes("playBtn.addEventListener(\"click\"")));
test("200Q 052: play event exists",()=>assert.ok(main.includes('audio.addEventListener("play"')));
test("200Q 053: pause event exists",()=>assert.ok(main.includes('audio.addEventListener("pause"')));
test("200Q 054: error event exists",()=>assert.ok(main.includes('audio.addEventListener("error"')));
test("200Q 055: canplay recovery exists",()=>assert.ok(main.includes('audio.addEventListener("canplay"')));
test("200Q 056: metadata handler exists",()=>assert.ok(main.includes('audio.addEventListener("loadedmetadata"')));
test("200Q 057: timeupdate handler exists",()=>assert.ok(main.includes('audio.addEventListener("timeupdate"')));
test("200Q 058: seek input handler exists",()=>assert.ok(main.includes('seek?.addEventListener("input"')));
test("200Q 059: mute handler exists",()=>assert.ok(main.includes('muteBtn?.addEventListener("click"')));
test("200Q 060: volume handler exists",()=>assert.ok(main.includes('vol?.addEventListener("input"')));
test("200Q 061: audio track key exists",()=>assert.ok(i18n.includes("fieldTrack:")));
test("200Q 062: audio track description key exists",()=>assert.ok(i18n.includes("fieldTrackP:")));
test("200Q 063: play key exists",()=>assert.ok(i18n.includes("fieldPlay:")));
test("200Q 064: pause key exists",()=>assert.ok(i18n.includes("fieldPause:")));
test("200Q 065: mute key exists",()=>assert.ok(i18n.includes("fieldMute:")));
test("200Q 066: unmute key exists",()=>assert.ok(i18n.includes("fieldUnmute:")));
test("200Q 067: audio error key exists",()=>assert.ok(i18n.includes("fieldAudioError:")));
test("200Q 068: flow kicker key exists",()=>assert.ok(i18n.includes("flowKicker:")));
test("200Q 069: flow heading key exists",()=>assert.ok(i18n.includes("flowH2:")));
test("200Q 070: flow lead key exists",()=>assert.ok(i18n.includes("flowLead:")));
test("200Q 071: flow current key exists",()=>assert.ok(i18n.includes("flowCurrent:")));
test("200Q 072: flow clock key exists",()=>assert.ok(i18n.includes("flowClock:")));
test("200Q 073: flow phase time key exists",()=>assert.ok(i18n.includes("flowPhaseTime:")));
test("200Q 074: flow controls label key exists",()=>assert.ok(i18n.includes("flowControlsLabel:")));
test("200Q 075: flow previous key exists",()=>assert.ok(i18n.includes("flowPrevious:")));
test("200Q 076: flow pause key exists",()=>assert.ok(i18n.includes("flowPause:")));
test("200Q 077: flow next key exists",()=>assert.ok(i18n.includes("flowNext:")));
test("200Q 078: flow reset key exists",()=>assert.ok(i18n.includes("flowReset:")));
test("200Q 079: flow start key exists",()=>assert.ok(i18n.includes("flowStart:")));
test("200Q 080: flow sequence key exists",()=>assert.ok(i18n.includes("flowSequence:")));
test("200Q 081: document has doctype",()=>assert.ok(/<!doctype html>/i.test(index)));
test("200Q 082: document declares language",()=>assert.ok(/<html[^>]+lang="(?:es|en)"/i.test(index)));
test("200Q 083: viewport metadata exists",()=>assert.ok(index.includes('name="viewport"')));
test("200Q 084: description metadata exists",()=>assert.ok(index.includes('name="description"')));
test("200Q 085: robots metadata exists",()=>assert.ok(index.includes('name="robots"')));
test("200Q 086: canonical link exists",()=>assert.ok(index.includes('rel="canonical"')));
test("200Q 087: OpenGraph title exists",()=>assert.ok(index.includes('property="og:title"')));
test("200Q 088: OpenGraph image exists",()=>assert.ok(index.includes('property="og:image"')));
test("200Q 089: Twitter card exists",()=>assert.ok(index.includes('name="twitter:card"')));
test("200Q 090: favicon exists",()=>assert.ok(index.includes('rel="icon"')));
test("200Q 091: font preconnect exists",()=>assert.ok(index.includes('rel="preconnect" href="https://fonts.googleapis.com"')));
test("200Q 092: theme control exists",()=>assert.ok(index.includes("data-set-theme")));
test("200Q 093: language control exists",()=>assert.ok(index.includes("data-set-lang")));
test("200Q 094: skip link exists",()=>assert.ok(index.includes('class="skip"')));
test("200Q 095: navigation has aria label",()=>assert.ok(/<nav[^>]+data-i18n-aria-label="navLabel"/.test(index)));
test("200Q 096: menu button exposes controls",()=>assert.ok(index.includes('aria-controls="nav"')));
test("200Q 097: reduced motion CSS exists",()=>assert.ok(css.includes("prefers-reduced-motion")));
test("200Q 098: no autoplay attribute",()=>assert.ok(!/<audio[^>]+\bautoplay\b/i.test(index)));
test("200Q 099: no insecure HTTP resources",()=>assert.ok(!/(?:href|src)\s*=\s*["']http:\/\//i.test(index + main + css)));
test("200Q 100: external targets use referrer policy",()=>assert.ok(!/<a[^>]+target="_blank"(?![^>]*rel="noreferrer")/i.test(index)));

