import assert from "node:assert/strict";
import test from "node:test";
import flowEngine from "../flow-engine.js";

const { PHASES, STATUS, YogaFlowEngine } = flowEngine;

test("100Q 01: phase start has canonical id",()=>assert.equal(PHASES[0].id,"start"));
test("100Q 02: phase centering has canonical id",()=>assert.equal(PHASES[1].id,"centering"));
test("100Q 03: phase breath has canonical id",()=>assert.equal(PHASES[2].id,"breath"));
test("100Q 04: phase warmup has canonical id",()=>assert.equal(PHASES[3].id,"warmup"));
test("100Q 05: phase pose-1 has canonical id",()=>assert.equal(PHASES[4].id,"pose-1"));
test("100Q 06: phase transition has canonical id",()=>assert.equal(PHASES[5].id,"transition"));
test("100Q 07: phase pose-2 has canonical id",()=>assert.equal(PHASES[6].id,"pose-2"));
test("100Q 08: phase cooldown has canonical id",()=>assert.equal(PHASES[7].id,"cooldown"));
test("100Q 09: phase savasana has canonical id",()=>assert.equal(PHASES[8].id,"savasana"));
test("100Q 10: phase finish has canonical id",()=>assert.equal(PHASES[9].id,"finish"));
test("100Q 11: phase start has canonical label",()=>assert.equal(PHASES[0].label,"START"));
test("100Q 12: phase centering has canonical label",()=>assert.equal(PHASES[1].label,"CENTERING"));
test("100Q 13: phase breath has canonical label",()=>assert.equal(PHASES[2].label,"BREATH"));
test("100Q 14: phase warmup has canonical label",()=>assert.equal(PHASES[3].label,"WARMUP"));
test("100Q 15: phase pose-1 has canonical label",()=>assert.equal(PHASES[4].label,"POSE"));
test("100Q 16: phase transition has canonical label",()=>assert.equal(PHASES[5].label,"TRANSITION"));
test("100Q 17: phase pose-2 has canonical label",()=>assert.equal(PHASES[6].label,"POSE"));
test("100Q 18: phase cooldown has canonical label",()=>assert.equal(PHASES[7].label,"COOLDOWN"));
test("100Q 19: phase savasana has canonical label",()=>assert.equal(PHASES[8].label,"SAVASANA"));
test("100Q 20: phase finish has canonical label",()=>assert.equal(PHASES[9].label,"FINISH"));
test("100Q 21: phase start has target 30s",()=>assert.equal(PHASES[0].durationSeconds,30));
test("100Q 22: phase centering has target 60s",()=>assert.equal(PHASES[1].durationSeconds,60));
test("100Q 23: phase breath has target 90s",()=>assert.equal(PHASES[2].durationSeconds,90));
test("100Q 24: phase warmup has target 120s",()=>assert.equal(PHASES[3].durationSeconds,120));
test("100Q 25: phase pose-1 has target 180s",()=>assert.equal(PHASES[4].durationSeconds,180));
test("100Q 26: phase transition has target 45s",()=>assert.equal(PHASES[5].durationSeconds,45));
test("100Q 27: phase pose-2 has target 180s",()=>assert.equal(PHASES[6].durationSeconds,180));
test("100Q 28: phase cooldown has target 90s",()=>assert.equal(PHASES[7].durationSeconds,90));
test("100Q 29: phase savasana has target 180s",()=>assert.equal(PHASES[8].durationSeconds,180));
test("100Q 30: phase finish has target 30s",()=>assert.equal(PHASES[9].durationSeconds,30));
test("100Q 31: phase start has practice cue",()=>assert.equal(PHASES[0].cue,"Llegar y preparar la práctica."));
test("100Q 32: phase centering has practice cue",()=>assert.equal(PHASES[1].cue,"Encontrar estabilidad y atención."));
test("100Q 33: phase breath has practice cue",()=>assert.equal(PHASES[2].cue,"Regular la respiración sin forzar."));
test("100Q 34: phase warmup has practice cue",()=>assert.equal(PHASES[3].cue,"Movilizar el cuerpo de forma progresiva."));
test("100Q 35: phase pose-1 has practice cue",()=>assert.equal(PHASES[4].cue,"Sostener la postura con respiración estable."));
test("100Q 36: phase transition has practice cue",()=>assert.equal(PHASES[5].cue,"Cambiar de forma con control y sin prisa."));
test("100Q 37: phase pose-2 has practice cue",()=>assert.equal(PHASES[6].cue,"Integrar fuerza, movilidad y atención."));
test("100Q 38: phase cooldown has practice cue",()=>assert.equal(PHASES[7].cue,"Reducir intensidad y dejar espacio a la respiración."));
test("100Q 39: phase savasana has practice cue",()=>assert.equal(PHASES[8].cue,"Soltar el esfuerzo y permanecer quieto."));
test("100Q 40: phase finish has practice cue",()=>assert.equal(PHASES[9].cue,"Cerrar la práctica sin romper la atención."));
test("100Q 41: navigation into start resolves deterministically",()=>{const e=new YogaFlowEngine();const s=e.goTo("start");assert.equal(s.index,0);assert.equal(s.phase,"start");assert.equal(s.total,10);});
test("100Q 42: navigation into centering resolves deterministically",()=>{const e=new YogaFlowEngine();const s=e.goTo("centering");assert.equal(s.index,1);assert.equal(s.phase,"centering");assert.equal(s.total,10);});
test("100Q 43: navigation into breath resolves deterministically",()=>{const e=new YogaFlowEngine();const s=e.goTo("breath");assert.equal(s.index,2);assert.equal(s.phase,"breath");assert.equal(s.total,10);});
test("100Q 44: navigation into warmup resolves deterministically",()=>{const e=new YogaFlowEngine();const s=e.goTo("warmup");assert.equal(s.index,3);assert.equal(s.phase,"warmup");assert.equal(s.total,10);});
test("100Q 45: navigation into pose-1 resolves deterministically",()=>{const e=new YogaFlowEngine();const s=e.goTo("pose-1");assert.equal(s.index,4);assert.equal(s.phase,"pose-1");assert.equal(s.total,10);});
test("100Q 46: navigation into transition resolves deterministically",()=>{const e=new YogaFlowEngine();const s=e.goTo("transition");assert.equal(s.index,5);assert.equal(s.phase,"transition");assert.equal(s.total,10);});
test("100Q 47: navigation into pose-2 resolves deterministically",()=>{const e=new YogaFlowEngine();const s=e.goTo("pose-2");assert.equal(s.index,6);assert.equal(s.phase,"pose-2");assert.equal(s.total,10);});
test("100Q 48: navigation into cooldown resolves deterministically",()=>{const e=new YogaFlowEngine();const s=e.goTo("cooldown");assert.equal(s.index,7);assert.equal(s.phase,"cooldown");assert.equal(s.total,10);});
test("100Q 49: navigation into savasana resolves deterministically",()=>{const e=new YogaFlowEngine();const s=e.goTo("savasana");assert.equal(s.index,8);assert.equal(s.phase,"savasana");assert.equal(s.total,10);});
test("100Q 50: navigation into finish resolves deterministically",()=>{const e=new YogaFlowEngine();const s=e.goTo("finish");assert.equal(s.index,9);assert.equal(s.phase,"finish");assert.equal(s.total,10);});
test("100Q 51: start snapshot exposes duration and cue",()=>{const e=new YogaFlowEngine();e.goTo("start");const s=e.snapshot();assert.equal(s.durationSeconds,30);assert.equal(s.cue,"Llegar y preparar la práctica.");});
test("100Q 52: centering snapshot exposes duration and cue",()=>{const e=new YogaFlowEngine();e.goTo("centering");const s=e.snapshot();assert.equal(s.durationSeconds,60);assert.equal(s.cue,"Encontrar estabilidad y atención.");});
test("100Q 53: breath snapshot exposes duration and cue",()=>{const e=new YogaFlowEngine();e.goTo("breath");const s=e.snapshot();assert.equal(s.durationSeconds,90);assert.equal(s.cue,"Regular la respiración sin forzar.");});
test("100Q 54: warmup snapshot exposes duration and cue",()=>{const e=new YogaFlowEngine();e.goTo("warmup");const s=e.snapshot();assert.equal(s.durationSeconds,120);assert.equal(s.cue,"Movilizar el cuerpo de forma progresiva.");});
test("100Q 55: pose-1 snapshot exposes duration and cue",()=>{const e=new YogaFlowEngine();e.goTo("pose-1");const s=e.snapshot();assert.equal(s.durationSeconds,180);assert.equal(s.cue,"Sostener la postura con respiración estable.");});
test("100Q 56: transition snapshot exposes duration and cue",()=>{const e=new YogaFlowEngine();e.goTo("transition");const s=e.snapshot();assert.equal(s.durationSeconds,45);assert.equal(s.cue,"Cambiar de forma con control y sin prisa.");});
test("100Q 57: pose-2 snapshot exposes duration and cue",()=>{const e=new YogaFlowEngine();e.goTo("pose-2");const s=e.snapshot();assert.equal(s.durationSeconds,180);assert.equal(s.cue,"Integrar fuerza, movilidad y atención.");});
test("100Q 58: cooldown snapshot exposes duration and cue",()=>{const e=new YogaFlowEngine();e.goTo("cooldown");const s=e.snapshot();assert.equal(s.durationSeconds,90);assert.equal(s.cue,"Reducir intensidad y dejar espacio a la respiración.");});
test("100Q 59: savasana snapshot exposes duration and cue",()=>{const e=new YogaFlowEngine();e.goTo("savasana");const s=e.snapshot();assert.equal(s.durationSeconds,180);assert.equal(s.cue,"Soltar el esfuerzo y permanecer quieto.");});
test("100Q 60: finish snapshot exposes duration and cue",()=>{const e=new YogaFlowEngine();e.goTo("finish");const s=e.snapshot();assert.equal(s.durationSeconds,30);assert.equal(s.cue,"Cerrar la práctica sin romper la atención.");});
test("100Q 61: start navigation neighbors are stable",()=>{const e=new YogaFlowEngine();e.goTo("start");const s=e.snapshot();assert.equal(s.previous,null);assert.equal(s.next,"centering");});
test("100Q 62: centering navigation neighbors are stable",()=>{const e=new YogaFlowEngine();e.goTo("centering");const s=e.snapshot();assert.equal(s.previous,"start");assert.equal(s.next,"breath");});
test("100Q 63: breath navigation neighbors are stable",()=>{const e=new YogaFlowEngine();e.goTo("breath");const s=e.snapshot();assert.equal(s.previous,"centering");assert.equal(s.next,"warmup");});
test("100Q 64: warmup navigation neighbors are stable",()=>{const e=new YogaFlowEngine();e.goTo("warmup");const s=e.snapshot();assert.equal(s.previous,"breath");assert.equal(s.next,"pose-1");});
test("100Q 65: pose-1 navigation neighbors are stable",()=>{const e=new YogaFlowEngine();e.goTo("pose-1");const s=e.snapshot();assert.equal(s.previous,"warmup");assert.equal(s.next,"transition");});
test("100Q 66: transition navigation neighbors are stable",()=>{const e=new YogaFlowEngine();e.goTo("transition");const s=e.snapshot();assert.equal(s.previous,"pose-1");assert.equal(s.next,"pose-2");});
test("100Q 67: pose-2 navigation neighbors are stable",()=>{const e=new YogaFlowEngine();e.goTo("pose-2");const s=e.snapshot();assert.equal(s.previous,"transition");assert.equal(s.next,"cooldown");});
test("100Q 68: cooldown navigation neighbors are stable",()=>{const e=new YogaFlowEngine();e.goTo("cooldown");const s=e.snapshot();assert.equal(s.previous,"pose-2");assert.equal(s.next,"savasana");});
test("100Q 69: savasana navigation neighbors are stable",()=>{const e=new YogaFlowEngine();e.goTo("savasana");const s=e.snapshot();assert.equal(s.previous,"cooldown");assert.equal(s.next,"finish");});
test("100Q 70: finish navigation neighbors are stable",()=>{const e=new YogaFlowEngine();e.goTo("finish");const s=e.snapshot();assert.equal(s.previous,"savasana");assert.equal(s.next,null);});
test("100Q 71: start progress is 0/9",()=>{const e=new YogaFlowEngine();e.goTo("start");assert.equal(e.snapshot().progress,0/9);});
test("100Q 72: centering progress is 1/9",()=>{const e=new YogaFlowEngine();e.goTo("centering");assert.equal(e.snapshot().progress,1/9);});
test("100Q 73: breath progress is 2/9",()=>{const e=new YogaFlowEngine();e.goTo("breath");assert.equal(e.snapshot().progress,2/9);});
test("100Q 74: warmup progress is 3/9",()=>{const e=new YogaFlowEngine();e.goTo("warmup");assert.equal(e.snapshot().progress,3/9);});
test("100Q 75: pose-1 progress is 4/9",()=>{const e=new YogaFlowEngine();e.goTo("pose-1");assert.equal(e.snapshot().progress,4/9);});
test("100Q 76: transition progress is 5/9",()=>{const e=new YogaFlowEngine();e.goTo("transition");assert.equal(e.snapshot().progress,5/9);});
test("100Q 77: pose-2 progress is 6/9",()=>{const e=new YogaFlowEngine();e.goTo("pose-2");assert.equal(e.snapshot().progress,6/9);});
test("100Q 78: cooldown progress is 7/9",()=>{const e=new YogaFlowEngine();e.goTo("cooldown");assert.equal(e.snapshot().progress,7/9);});
test("100Q 79: savasana progress is 8/9",()=>{const e=new YogaFlowEngine();e.goTo("savasana");assert.equal(e.snapshot().progress,8/9);});
test("100Q 80: finish progress is 9/9",()=>{const e=new YogaFlowEngine();e.goTo("finish");assert.equal(e.snapshot().progress,9/9);});
test("100Q 81: start direct navigation is running except finish",()=>{const e=new YogaFlowEngine();const s=e.goTo("start");assert.equal(s.status,STATUS.RUNNING);});
test("100Q 82: centering direct navigation is running except finish",()=>{const e=new YogaFlowEngine();const s=e.goTo("centering");assert.equal(s.status,STATUS.RUNNING);});
test("100Q 83: breath direct navigation is running except finish",()=>{const e=new YogaFlowEngine();const s=e.goTo("breath");assert.equal(s.status,STATUS.RUNNING);});
test("100Q 84: warmup direct navigation is running except finish",()=>{const e=new YogaFlowEngine();const s=e.goTo("warmup");assert.equal(s.status,STATUS.RUNNING);});
test("100Q 85: pose-1 direct navigation is running except finish",()=>{const e=new YogaFlowEngine();const s=e.goTo("pose-1");assert.equal(s.status,STATUS.RUNNING);});
test("100Q 86: transition direct navigation is running except finish",()=>{const e=new YogaFlowEngine();const s=e.goTo("transition");assert.equal(s.status,STATUS.RUNNING);});
test("100Q 87: pose-2 direct navigation is running except finish",()=>{const e=new YogaFlowEngine();const s=e.goTo("pose-2");assert.equal(s.status,STATUS.RUNNING);});
test("100Q 88: cooldown direct navigation is running except finish",()=>{const e=new YogaFlowEngine();const s=e.goTo("cooldown");assert.equal(s.status,STATUS.RUNNING);});
test("100Q 89: savasana direct navigation is running except finish",()=>{const e=new YogaFlowEngine();const s=e.goTo("savasana");assert.equal(s.status,STATUS.RUNNING);});
test("100Q 90: finish direct navigation is running except finish",()=>{const e=new YogaFlowEngine();const s=e.goTo("finish");assert.equal(s.status,STATUS.FINISHED);});
test("100Q 91: engine starts exactly at START",()=>{const e=new YogaFlowEngine();const s=e.start();assert.equal(s.phase,"start");assert.equal(s.index,0);assert.equal(s.status,STATUS.RUNNING);});
test("100Q 92: engine start resets history",()=>{const e=new YogaFlowEngine();e.start();e.next();e.start();assert.deepEqual(e.history,["start"]);});
test("100Q 93: engine pause freezes index",()=>{const e=new YogaFlowEngine();e.start();e.next();const i=e.snapshot().index;e.pause();assert.equal(e.snapshot().index,i);assert.equal(e.snapshot().status,STATUS.PAUSED);});
test("100Q 94: engine resume restores running state",()=>{const e=new YogaFlowEngine();e.start();e.pause();const s=e.resume();assert.equal(s.status,STATUS.RUNNING);assert.equal(s.phase,"start");});
test("100Q 95: paused direct navigation remains paused",()=>{const e=new YogaFlowEngine();e.start();e.pause();const s=e.goTo("cooldown");assert.equal(s.status,STATUS.PAUSED);assert.equal(s.phase,"cooldown");});
test("100Q 96: finished state rejects previous",()=>{const e=new YogaFlowEngine();e.start();while(e.status!==STATUS.FINISHED)e.next();const s=e.previous();assert.equal(s.status,STATUS.FINISHED);assert.equal(s.phase,"finish");});
test("100Q 97: finished state rejects next",()=>{const e=new YogaFlowEngine();e.start();while(e.status!==STATUS.FINISHED)e.next();const before=e.snapshot();assert.deepEqual(e.next(),before);});
test("100Q 98: reset returns clean idle START",()=>{const e=new YogaFlowEngine();e.start();while(e.status!==STATUS.FINISHED)e.next();const s=e.reset();assert.equal(s.status,STATUS.IDLE);assert.equal(s.phase,"start");assert.equal(e.history.length,0);});
test("100Q 99: snapshot is immutable",()=>{const e=new YogaFlowEngine();const s=e.snapshot();assert.throws(()=>{s.index=9;},TypeError);});
test("100Q 100: all phase definitions are frozen",()=>{assert.ok(Object.isFrozen(PHASES));assert.ok(PHASES.every((p)=>Object.isFrozen(p)));});
